### ISSUE TITLE
Add a footer section 

### ISSUE THREAD

**Issue by yeshwanth-ds** [BhattAnsh/Quiz-Quest#61] opened 2024-10-10 16:36 UTC
Adding a footer section with relavent information and links.

I would like you to assign me this task and hacktoberfest and gssoc-ext with level tag

**Comment by student-nitjalandhar** [comment] 2024-10-11 08:02
@yeshwanth-ds please assign this to me

**Comment by SatyamTiwari069** [comment] 2024-10-12 10:39
please assign me the task as for gssoc24 extd

**Comment by tarunkumar2005** [comment] 2024-10-16 15:50
@BhattAnsh I can see the issue is open from last week still not fixed can you assign this to me i will work on this issue.

**Comment by SaanyaGarg5** [comment] 2024-10-16 18:45
you can assign this task to me.. i can design a very nice footer

**Closed** 2024-10-31 20:28 UTC
Labels: gssoc-ext, level3, hacktoberfest-accepted
