### ISSUE TITLE
Building Registration Form

### ISSUE THREAD

**Issue by tanmayghosh01-hue** [BhattAnsh/Quiz-Quest#15] opened 2024-10-02 19:49 UTC
I will create Login and Registration form based on given UI.

**Comment by ravi-kumar2003** [comment] 2024-10-04 05:44
I came across this issue, and I would love to help contribute to resolving it.

**Comment by Sarthakkashyapp** [comment] 2024-10-07 19:04
Hi @BhattAnsh I would like to contribute on this issue

**Comment by tarunkumar2005** [comment] 2024-10-16 15:49
@BhattAnsh The issue is assigned from two weeks still not fixed can you assign this to me i will work on this issue.

**Comment by CodeVoyge** [comment] 2024-10-18 19:15
I would like to contribute on this issue , could you please assign this to me??

**Comment by harshbhar0629** [comment] 2024-10-27 14:55
@BhattAnsh Please assign to me:)

**Closed** 2024-10-31 20:20 UTC
Labels: gssoc-ext, level3, hacktoberfest-accepted
