### ISSUE TITLE
Create Detailed "About" Section for Home Page

### ISSUE THREAD

**Issue by samar12-rad** [BhattAnsh/Quiz-Quest#47] opened 2024-10-08 04:57 UTC
Description:

We need to create a comprehensive "About" section on the home page of our quiz-taking website. This section should clearly explain the processes for users to join a quiz and to create their own quizzes.

Tasks:

Joining a Quiz:

Registration Process:
Explain the need for users to register on the website.
Outline the registration steps (e.g., providing email, username, password).
Mention any verification process (e.g., email confirmation).
Receiving the Join Link:
Explain that after registration, users will receive a unique link to join the quiz.
Provide instructions on how to access and use the link.
Creating a Quiz:

Requirements to Create a Quiz:
Mention if users need to register before creating a quiz.
Outline any permissions or roles required (e.g., admin, quiz creator).
Steps to Create a Quiz:
Provide a step-by-step guide on how to create a quiz (e.g., navigating to the quiz creation page, filling in quiz details such as title, description, and questions).

Additional Information:
Acceptance Criteria:

The "About" section is informative, clear, and easy to navigate.
The section is visually appealing and consistent with the website's design.
User feedback is gathered to ensure the content is helpful and easy to understand.

**Comment by tarunkumar2005** [comment] 2024-10-16 15:48
@BhattAnsh I can see the issue is open from last week still not fixed can you assign this to me i will work on this issue.

**Comment by SaanyaGarg5** [comment] 2024-10-16 18:45
you can assign this task to me..

**Comment by CodeVoyge** [comment] 2024-10-18 19:14
Hey, i would like to work on this project , can you please assign it to me?

**Closed** 2024-10-31 20:28 UTC
Labels: gssoc-ext, level3, hacktoberfest-accepted
